// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_encoding_array`, `tokenize`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EncodingType`

Future<(Tokenizer, Session)> loadArtifacts() =>
    RustLib.instance.api.crateApiAchoLoadArtifacts();

Future<Array2F32> runInference(
        {required List<String> text,
        required Session model,
        required Tokenizer tokenizer}) =>
    RustLib.instance.api.crateApiAchoRunInference(
        text: text, model: model, tokenizer: tokenizer);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Array2 < f32 >>>
abstract class Array2F32 implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Session>>
abstract class Session implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Tokenizer>>
abstract class Tokenizer implements RustOpaqueInterface {}
