// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<(Tokenizer, Session)> loadArtifacts(
        {required String modelPath, required String tokenizerPath}) =>
    RustLib.instance.api.crateApiAchoLoadArtifacts(
        modelPath: modelPath, tokenizerPath: tokenizerPath);

Future<Array2I64> getEncodingArray(
        {required List<Encoding> encodings,
        required EncodingType encodingType}) =>
    RustLib.instance.api.crateApiAchoGetEncodingArray(
        encodings: encodings, encodingType: encodingType);

Future<(Array2I64, Array2I64)> tokenize(
        {required List<String> texts, required Tokenizer tokenizer}) =>
    RustLib.instance.api
        .crateApiAchoTokenize(texts: texts, tokenizer: tokenizer);

Future<Array2F32> runInference(
        {required List<String> text,
        required Session model,
        required Tokenizer tokenizer}) =>
    RustLib.instance.api.crateApiAchoRunInference(
        text: text, model: model, tokenizer: tokenizer);

Future<List<SimilarityScore>> similarity(
        {required List<String> query,
        required List<String> texts,
        required String modelPath,
        required String tokenizerPath,
        required int topK}) =>
    RustLib.instance.api.crateApiAchoSimilarity(
        query: query,
        texts: texts,
        modelPath: modelPath,
        tokenizerPath: tokenizerPath,
        topK: topK);

Future<List<SimilarityScore>> getTopK(
        {required List<double> scores, required BigInt k}) =>
    RustLib.instance.api.crateApiAchoGetTopK(scores: scores, k: k);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Array2 < f32 >>>
abstract class Array2F32 implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Array2 < i64 >>>
abstract class Array2I64 implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Encoding>>
abstract class Encoding implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Session>>
abstract class Session implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Tokenizer>>
abstract class Tokenizer implements RustOpaqueInterface {}

enum EncodingType {
  ids,
  attentionMask,
  ;
}

class SimilarityScore {
  final BigInt index;
  final double score;

  const SimilarityScore({
    required this.index,
    required this.score,
  });

  @override
  int get hashCode => index.hashCode ^ score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimilarityScore &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          score == other.score;
}
