// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PathBuf>>
abstract class PathBuf implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SearchFn>>
abstract class SearchFn implements RustOpaqueInterface {
  PathBuf get pathToIndex;

  set pathToIndex(PathBuf pathToIndex);

  Future<void> deleteIndex();

  Future<void> ingestPdfDir({required PathBuf filePath});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Creates a new SearchFn instance and initializes the index on disk
  static Future<SearchFn> newInstance({required PathBuf path}) =>
      RustLib.instance.api.crateApiKeywordSearchSearchFnNew(path: path);
}
