// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class SearchFn {
  final String pathToIndex;

  const SearchFn({
    required this.pathToIndex,
  });

  ///For reset functionality, clearing index
  Future<void> deleteIndex() =>
      RustLib.instance.api.crateApiKeywordSearchSearchFnDeleteIndex(
        that: this,
      );

  Future<void> ingestPdfDir({required Path dirPath}) => RustLib.instance.api
      .crateApiKeywordSearchSearchFnIngestPdfDir(that: this, dirPath: dirPath);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  Future<SearchFn> newInstance() =>
      RustLib.instance.api.crateApiKeywordSearchSearchFnNew(
        that: this,
      );

  @override
  int get hashCode => pathToIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchFn &&
          runtimeType == other.runtimeType &&
          pathToIndex == other.pathToIndex;
}
