// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `TantivyApi`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

void initTantivy({required String dirPath}) =>
    RustLib.instance.api.crateApiTantivyInitTantivy(dirPath: dirPath);

Future<void> addDocument({required Document doc}) =>
    RustLib.instance.api.crateApiTantivyAddDocument(doc: doc);

Future<List<SearchResult>> searchDocuments(
        {required String query, required BigInt topK}) =>
    RustLib.instance.api
        .crateApiTantivySearchDocuments(query: query, topK: topK);

Document? getDocumentById({required String id}) =>
    RustLib.instance.api.crateApiTantivyGetDocumentById(id: id);

Future<void> updateDocument({required Document doc}) =>
    RustLib.instance.api.crateApiTantivyUpdateDocument(doc: doc);

Future<void> deleteDocument({required String id}) =>
    RustLib.instance.api.crateApiTantivyDeleteDocument(id: id);

Future<void> addDocumentsBatch({required List<Document> docs}) =>
    RustLib.instance.api.crateApiTantivyAddDocumentsBatch(docs: docs);

Future<void> deleteDocumentsBatch({required List<String> ids}) =>
    RustLib.instance.api.crateApiTantivyDeleteDocumentsBatch(ids: ids);

void commit() => RustLib.instance.api.crateApiTantivyCommit();

Future<void> addDocumentNoCommit({required Document doc}) =>
    RustLib.instance.api.crateApiTantivyAddDocumentNoCommit(doc: doc);

Future<void> deleteDocumentNoCommit({required String id}) =>
    RustLib.instance.api.crateApiTantivyDeleteDocumentNoCommit(id: id);

class Document {
  final String id;
  final String text;

  const Document({
    required this.id,
    required this.text,
  });

  @override
  int get hashCode => id.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Document &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          text == other.text;
}

class SearchResult {
  final double score;
  final Document doc;

  const SearchResult({
    required this.score,
    required this.doc,
  });

  @override
  int get hashCode => score.hashCode ^ doc.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResult &&
          runtimeType == other.runtimeType &&
          score == other.score &&
          doc == other.doc;
}
